 export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST"
 export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
 export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL"

 export const ONE_PRODUCT_REQUEST="ONE_PRODUCT_REQUEST"
 export const ONE_PRODUCT_SUCCESS="ONE_PRODUCT_SUCCESS"
 export const ONE_PRODUCT_FAIL="ONE_PRODUCT_FAIL"
 
 export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
 export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
 export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"

 export const CV_REQUEST="CV_REQUEST"
 export const CV_SUCCESS="CV_SUCCESS"
 export const CV_FAIL="CV_FAIL"



 export const CLEAR_ERROS="CLEAR_ERROS"