const mongose=require('mongoose');
const orderSchema= new mongose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pinCode:
        {
            type:Number,
            required:true
        },
        phoneNo:{
            type:Number,
            required:true
        }
    },

    orderItems:[
        {
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
       image:{
            type:String,
            required:true
        },
        product:{
            type:mongose.Schema.ObjectId,
            ref:"Product",
            required:true
        },


    }
    ],

    user:{
        type:mongose.Schema.ObjectId,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        },
        paidAt:{
            type:Date,
            default:Date.now(),
            required:true
        },
        itemsPrice:{
            type:Number,
            required:true,
            default:0
        },
        taxPrice:{
            type:Number,
            required:true,
            default:0

        },
        shippingPrice:{
            type:Number,
            required:true,
            default:0
        },
        totalPrice:{
            type:Number,
            required:true,
            default:0
        },
    },

    orderStatus:{
        type:String,
        required:true,
        default:"processing"
    },
    DeliveredAt:Date,
    createdAt:{
        type:Date,
        default:Date.now()
    },
})

module.exports=mongose.model("Order",orderSchema)